export const ROUTES = {
    HOME: "/",
    PRODUCT_DETAIL: "/productDetail",
    PRODUCT_LIST: "/productList",
    CART: "/cart",
    CHECKOUT: "/checkout",
    WISH_LIST: "/wishlist",
    TRACKING: "/tracking",
    PROFILE: "/profile",
    SHOP: "/shop",
    CATEGORY: "/category",
    WEB_REVIEW: "/web-review",
    REGISTER_SHOP: "/register-shop",
    SIGN_IN: "/sign-in",
    SIGN_UP: "/sign-up",
    OTP: "/otp",
    OTP_PHONE: "/otpPhone",
}